import { _electron as electron, expect } from '@playwright/test';
import { mkdtempSync, mkdirSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const data=mkdtempSync(join(tmpdir(),'wa-ui-smoke-'));
mkdirSync('smoke-output',{recursive:true});
const errors=[];
const launch=()=>electron.launch({executablePath:process.env.APP_EXE,args:process.env.APP_EXE?[]:['.'],env:{...process.env,WASCHEDULER_SMOKE:'1',WASCHEDULER_DATA:data},timeout:60000});
let app=await launch();
try {
  let page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error') console.log('Renderer error:',msg.text());});
  console.log('Preload API available:',await page.evaluate(()=>typeof window.waScheduler?.call));
  await expect(page.locator('#connection')).toHaveText('WhatsApp connected');
  await expect(page.locator('#schedule-list .empty')).toContainText('No schedules yet');
  await page.locator('#new').click();
  await page.locator('#save').click();await expect(page.locator('#form-error')).toContainText('Choose a recipient');
  await page.locator('#recipient').selectOption('380501234567@s.whatsapp.net');
  await page.locator('#message').fill('Доброе утро\n🙂');
  await page.locator('#test').click();await expect(page.locator('#test-result')).toContainText('sent');
  await page.locator('#schedule-kind').selectOption('weekly');
  await page.locator('#weekdays input[value="1"]').check();
  await page.locator('#from').fill('08:00');await page.locator('#to').fill('08:00');await page.locator('#interval').fill('04:00');
  await page.locator('#save').click();await expect(page.locator('.card')).toHaveCount(1);
  await expect(page.locator('.card')).toContainText('08:00–08:00');
  await page.locator('.card button').filter({hasText:'Edit'}).click();
  await page.locator('#to').fill('07:00');await page.locator('#save').click();await expect(page.locator('#form-error')).toContainText('cannot be earlier');
  await page.locator('#to').fill('08:00');
  await page.locator('#message').fill('Доброе утро\n🙂 — изменено');
  await page.locator('#save').click();await expect(page.locator('.card')).toContainText('изменено');
  await page.locator('.toggle-label input').uncheck();await expect(page.locator('.card')).toContainText('Paused');
  await page.locator('.toggle-label input').check();await expect(page.locator('.card')).toContainText('Active');
  await page.locator('#new').click();await page.locator('input[name="recipient-kind"][value="group"]').check();
  await expect(page.locator('#recipient option')).toHaveCount(2);
  await page.locator('#recipient').selectOption('120363000000000000@g.us');await page.locator('#message').fill('Group: тест');
  await page.locator('#save').click();await expect(page.locator('.card')).toHaveCount(2);
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('.card').nth(1).getByRole('button',{name:'Delete',exact:true}).click();
  await expect(page.locator('.card')).toHaveCount(1);
  await page.locator('#new').click();await page.locator('input[name="recipient-kind"][value="group"]').check();
  await page.locator('#recipient').selectOption('120363000000000000@g.us');await page.locator('#message').fill('Group: тест');
  await page.locator('#save').click();await expect(page.locator('.card')).toHaveCount(2);
  await page.screenshot({path:'smoke-output/schedules.png',fullPage:true});
  await page.locator('[data-tab="history"]').click();await expect(page.locator('#history-list')).toContainText('Sent');
  await page.locator('[data-tab="settings"]').click();await page.locator('#grace').selectOption('15');await page.locator('#autostart').uncheck();await page.locator('#save-settings').click();
  await page.locator('#copy-diagnostics').click();
  await expect(page.locator('#feedback')).toContainText('Diagnostics copied');
  const report=await app.evaluate(async({clipboard})=>JSON.parse(await clipboard.readText()));
  expect(report.platform).toBe('win32');expect(report.connection).toBe('WhatsApp connected');expect(report.sync.personalChats).toBe(1);expect(report.sync.groups).toBe(1);
  expect(JSON.stringify(report)).not.toContain('380501234567');expect(JSON.stringify(report)).not.toContain('Доброе утро');expect(JSON.stringify(report)).not.toContain('auth');
  const secured=await app.evaluate(async({safeStorage})=>{const plain='sensitive-fixture';const cipher=await safeStorage.encryptStringAsync(plain);const restored=await safeStorage.decryptStringAsync(cipher);return {matches:restored.result===plain,encrypted:!cipher.includes(Buffer.from(plain))};});
  expect(secured).toEqual({matches:true,encrypted:true});
  await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].close();});
  expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible())).toBe(false);
  await app.close();
  app=await launch();page=await app.firstWindow();
  await expect(page.locator('.card')).toHaveCount(2);
  await page.locator('[data-tab="settings"]').click();await expect(page.locator('#grace')).toHaveValue('15');await expect(page.locator('#autostart')).not.toBeChecked();
  const stored=JSON.parse(readFileSync(join(data,'state.json'),'utf8'));
  expect(stored.schedules[0].text).toBe('Доброе утро\n🙂 — изменено');
  page.once('dialog', dialog => dialog.dismiss());
  await page.locator('#logout').click();
  await expect(page.locator('#connection')).toHaveText('WhatsApp connected');
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#logout').click();
  await expect(page.locator('#connection')).toHaveText('Signed out');
  await expect(page.locator('#logout')).toBeDisabled();
  await expect(page.locator('#reconnect')).toHaveText('Connect WhatsApp');
  const signedOut = JSON.parse(readFileSync(join(data,'state.json'),'utf8'));
  expect(signedOut.recipients).toEqual([]);
  expect(signedOut.recipientMetadata).toEqual({});
  expect(signedOut.schedules).toHaveLength(2);
  expect(signedOut.history.length).toBeGreaterThan(0);
  expect(signedOut.settings.paused).toBe(true);
  await page.screenshot({path:'smoke-output/signed-out.png',fullPage:true});
  expect(errors).toEqual([]);
  console.log('Installed Windows app: renderer CRUD, validation, personal/group separation, test-send mock, Unicode, settings, DPAPI roundtrip, tray close, restart persistence passed. WhatsApp network not mocked as verified.');
} catch(e) { const windows=app.windows();if(windows.length) await windows[0].screenshot({path:'smoke-output/failure.png'}).catch(()=>{});console.log('Smoke failure:',e.message);console.log('Renderer errors:',errors);throw e; } finally { await app.close(); }
