; Per-user NSIS installer. Keep user data on uninstall for schedules and session continuity.
; Generated by electron-builder with allowToChangeInstallationDirectory=true.
!macro customInstall
  DetailPrint "WhatsApp Scheduler: installation completed."
!macroend
